package burp.reporting;

import burp.integrations.OwaspMapping;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * ReportGenerator: Generates comprehensive vulnerability reports in Markdown format.
 * Includes all relevant details: summary, steps to reproduce, request/response, impact, remediation, and OWASP mapping.
 */
public class ReportGenerator {
    private final DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    
    /**
     * Generate a complete vulnerability report.
     */
    public String generateReport(String vulnerabilityTitle, String severity, String summary,
                                String stepsToReproduce, String request, String response,
                                String impact, String remediation, String owaspCategory) {
        
        StringBuilder report = new StringBuilder();
        
        // Header
        report.append("# Security Vulnerability Report\n\n");
        report.append("**Generated**: ").append(LocalDateTime.now().format(dateFormatter)).append("\n");
        report.append("**Extension**: BurpXcelerator\n\n");
        
        // Title and Severity
        report.append("## ").append(vulnerabilityTitle).append("\n\n");
        report.append("**Severity**: ").append(severity).append("\n");
        report.append("**OWASP Category**: ").append(owaspCategory).append("\n\n");
        
        // Summary
        report.append("### Summary\n\n");
        report.append(summary).append("\n\n");
        
        // Steps to Reproduce
        report.append("### Steps to Reproduce\n\n");
        report.append(stepsToReproduce).append("\n\n");
        
        // Request
        report.append("### HTTP Request\n\n");
        report.append("```\n");
        report.append(request).append("\n");
        report.append("```\n\n");
        
        // Response
        report.append("### HTTP Response\n\n");
        report.append("```\n");
        report.append(response).append("\n");
        report.append("```\n\n");
        
        // Impact
        report.append("### Impact\n\n");
        report.append(impact).append("\n\n");
        
        // Remediation
        report.append("### Remediation\n\n");
        report.append(remediation).append("\n\n");
        
        // Proof of Concept
        report.append("### Proof of Concept\n\n");
        report.append("1. Use the steps outlined above to reproduce the vulnerability\n");
        report.append("2. Verify the impact by examining the response\n");
        report.append("3. Implement the remediation measures\n\n");
        
        // Risk Assessment
        report.append("### Risk Assessment\n\n");
        report.append("This vulnerability allows an attacker to: \n");
        report.append("- Compromise application security\n");
        report.append("- Gain unauthorized access\n");
        report.append("- Steal or manipulate sensitive data\n\n");
        
        // References
        report.append("### References\n\n");
        report.append("- [OWASP Top 10 2021](https://owasp.org/Top10/)\n");
        report.append("- [OWASP Testing Guide](https://owasp.org/www-project-web-security-testing-guide/)\n\n");
        
        // Footer
        report.append("---\n");
        report.append("*Report generated by BurpXcelerator*\n");
        
        return report.toString();
    }
    
    /**
     * Generate a simplified report with minimal information.
     */
    public String generateSimpleReport(String vulnerabilityTitle, String severity,
                                      String summary, String owaspCategory) {
        
        StringBuilder report = new StringBuilder();
        
        report.append("# ").append(vulnerabilityTitle).append("\n\n");
        report.append("**Severity**: ").append(severity).append("\n");
        report.append("**OWASP**: ").append(owaspCategory).append("\n");
        report.append("**Date**: ").append(LocalDateTime.now().format(dateFormatter)).append("\n\n");
        report.append(summary).append("\n");
        
        return report.toString();
    }
    
    /**
     * Map vulnerability to OWASP category.
     */
    public static String mapToOWASP(String vulnerability) {
        return OwaspMapping.getOwaspCategory(vulnerability);
    }
}

